In [155]:
#1- Download the Kears+Tensorflow tutorial from Canvas. Import all required modules including the following:
!pip install tensorflow
!pip install keras

from  keras.wrappers.scikit_learn  import  KerasClassifier
from  sklearn.model_selection  import  GridSearchCV
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
import numpy as np


In [156]:
# Keras will download MNIST digit dataset for us:
from keras.datasets import mnist

#split into testing and training
(X_train, y_train), (X_test, y_test) = mnist.load_data()

#before reshaping
print(X_train.shape)
print(X_test.shape)


#2- Import the minst dataset, and split it into testing and training as we saw in the tutorial. Then, reshape each sample into a row vector, and scale it by dividing by 255.
# Reshape each image pixels into a row of feature table with 28*28=784 features (each pixel is a feature):
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)


# simply scale the features to the range of [0,1]: by converting first
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

# output label: 
print (y_train.shape)
#printing out the first 10 samples
print (y_train[:10])

print("this is X_train: ", X_train)
print("this is y_train: ", y_train)



(60000, 28, 28)
(10000, 28, 28)
(60000,)
[5 0 4 1 9 2 1 3 1 4]
this is X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
this is y_train:  [5 0 4 ... 5 6 8]


In [157]:
#3- Perform OneHotEncoding for the label y. So, your label will be a vector of 10 elements for each data sample.

# import some utilities to transform/preprocess our data: 
#our neural network will have 10 output
from keras.utils import np_utils
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [158]:
#4- Now, define a function called model_creator. 
#This function will define, create, and compile your neural network model according to your structure, 
#and then return the built model as the output. For the ANN neurons/layers, 
#use the same structure as we had in the tutorial:

#the input are pixels
input_size = 784
#one hidden layer with 100 neurons
hidden_neurons = 100 
output_size = 10



def model_creator():
  # define:

    model = Sequential()

    # design the structure:
    
    #we are going to design the ANN Structure with 784 inputs, 10 outputs and 100 neuron in the hidden layer
    #---------------------------------------------------------------
    #first layer is the input layer
    #the input layers are simply just inputs and does not do any processing so we do not need to define the input layer

    #second layer is the hidden layer:

    model.add(Dense(hidden_neurons, input_dim = input_size))    
    model.add(Activation('sigmoid'))
    
    #third layer is the output layer:
    model.add(Dense(output_size, input_dim = hidden_neurons))
    model.add(Activation('softmax'))
    
   # compile:

    model.compile(loss='categorical_crossentropy', optimizer='adam',  metrics=['accuracy'])

   # return: 

    

    return model 

In [159]:
#5- Fix the random state for reproducibility:     
seed = 2
np.random.seed(seed)

In [160]:
#6- Use KerasClassifier class to wrap your model as an object:

model = KerasClassifier(build_fn = model_creator, verbose=2)

<ipython-input-160-254a7301f958>:3: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn = model_creator, verbose=2)


In [161]:
#7- Now, run sklearn GridSearch to find the best batch_size and epochs. 
#Search in this range: batch_size = [30 , 50 , 100 ] , epochs = [10 , 15 , 20].  
#In your GridSearch, the estimator is the above model,  
#the scoring should be 'neg_log_loss', and you have to use 10-fold CV.
epochs = [10,15,20]
batch_size = [30,50,100]

from sklearn.model_selection import GridSearchCV

param_grid = dict(batch_size=batch_size, epochs=epochs)
gridTrain = GridSearchCV(model, param_grid, cv = 10, scoring = 'neg_log_loss')
gridTrain.fit(X_train, y_train)





Epoch 1/10
1800/1800 - 2s - loss: 0.4351 - accuracy: 0.8898 - 2s/epoch - 916us/step
Epoch 2/10
1800/1800 - 2s - loss: 0.2105 - accuracy: 0.9394 - 2s/epoch - 835us/step
Epoch 3/10
1800/1800 - 2s - loss: 0.1588 - accuracy: 0.9547 - 2s/epoch - 883us/step
Epoch 4/10
1800/1800 - 2s - loss: 0.1267 - accuracy: 0.9636 - 2s/epoch - 853us/step
Epoch 5/10
1800/1800 - 1s - loss: 0.1042 - accuracy: 0.9700 - 1s/epoch - 804us/step
Epoch 6/10
1800/1800 - 1s - loss: 0.0875 - accuracy: 0.9751 - 1s/epoch - 799us/step
Epoch 7/10
1800/1800 - 1s - loss: 0.0743 - accuracy: 0.9792 - 1s/epoch - 802us/step
Epoch 8/10
1800/1800 - 1s - loss: 0.0634 - accuracy: 0.9825 - 1s/epoch - 812us/step
Epoch 9/10
1800/1800 - 1s - loss: 0.0545 - accuracy: 0.9856 - 1s/epoch - 803us/step
Epoch 10/10
1800/1800 - 1s - loss: 0.0472 - accuracy: 0.9872 - 1s/epoch - 811us/step
Epoch 1/10
1800/1800 - 2s - loss: 0.4370 - accuracy: 0.8874 - 2s/epoch - 907us/step
Epoch 2/10
1800/1800 - 1s - loss: 0.2123 - accuracy: 0.9394 - 1s/epoch - 81

Epoch 9/10
1800/1800 - 1s - loss: 0.0521 - accuracy: 0.9854 - 1s/epoch - 816us/step
Epoch 10/10
1800/1800 - 1s - loss: 0.0448 - accuracy: 0.9883 - 1s/epoch - 831us/step
Epoch 1/15
1800/1800 - 2s - loss: 0.4296 - accuracy: 0.8920 - 2s/epoch - 947us/step
Epoch 2/15
1800/1800 - 2s - loss: 0.2115 - accuracy: 0.9392 - 2s/epoch - 862us/step
Epoch 3/15
1800/1800 - 1s - loss: 0.1593 - accuracy: 0.9537 - 1s/epoch - 827us/step
Epoch 4/15
1800/1800 - 1s - loss: 0.1267 - accuracy: 0.9635 - 1s/epoch - 815us/step
Epoch 5/15
1800/1800 - 2s - loss: 0.1032 - accuracy: 0.9699 - 2s/epoch - 835us/step
Epoch 6/15
1800/1800 - 2s - loss: 0.0853 - accuracy: 0.9756 - 2s/epoch - 835us/step
Epoch 7/15
1800/1800 - 1s - loss: 0.0724 - accuracy: 0.9792 - 1s/epoch - 819us/step
Epoch 8/15
1800/1800 - 1s - loss: 0.0614 - accuracy: 0.9834 - 1s/epoch - 822us/step
Epoch 9/15
1800/1800 - 1s - loss: 0.0524 - accuracy: 0.9860 - 1s/epoch - 813us/step
Epoch 10/15
1800/1800 - 1s - loss: 0.0455 - accuracy: 0.9876 - 1s/epoch - 8

1800/1800 - 1s - loss: 0.0814 - accuracy: 0.9773 - 1s/epoch - 777us/step
Epoch 7/15
1800/1800 - 1s - loss: 0.0686 - accuracy: 0.9806 - 1s/epoch - 776us/step
Epoch 8/15
1800/1800 - 1s - loss: 0.0580 - accuracy: 0.9846 - 1s/epoch - 790us/step
Epoch 9/15
1800/1800 - 1s - loss: 0.0498 - accuracy: 0.9864 - 1s/epoch - 799us/step
Epoch 10/15
1800/1800 - 1s - loss: 0.0426 - accuracy: 0.9891 - 1s/epoch - 765us/step
Epoch 11/15
1800/1800 - 1s - loss: 0.0361 - accuracy: 0.9913 - 1s/epoch - 771us/step
Epoch 12/15
1800/1800 - 1s - loss: 0.0312 - accuracy: 0.9928 - 1s/epoch - 780us/step
Epoch 13/15
1800/1800 - 1s - loss: 0.0268 - accuracy: 0.9938 - 1s/epoch - 777us/step
Epoch 14/15
1800/1800 - 1s - loss: 0.0227 - accuracy: 0.9953 - 1s/epoch - 780us/step
Epoch 15/15
1800/1800 - 1s - loss: 0.0195 - accuracy: 0.9963 - 1s/epoch - 785us/step
Epoch 1/15
1800/1800 - 2s - loss: 0.4260 - accuracy: 0.8911 - 2s/epoch - 872us/step
Epoch 2/15
1800/1800 - 1s - loss: 0.2065 - accuracy: 0.9417 - 1s/epoch - 798us/st

Epoch 4/20
1800/1800 - 1s - loss: 0.1237 - accuracy: 0.9645 - 1s/epoch - 828us/step
Epoch 5/20
1800/1800 - 1s - loss: 0.1015 - accuracy: 0.9710 - 1s/epoch - 822us/step
Epoch 6/20
1800/1800 - 1s - loss: 0.0849 - accuracy: 0.9759 - 1s/epoch - 818us/step
Epoch 7/20
1800/1800 - 1s - loss: 0.0723 - accuracy: 0.9799 - 1s/epoch - 809us/step
Epoch 8/20
1800/1800 - 1s - loss: 0.0618 - accuracy: 0.9832 - 1s/epoch - 820us/step
Epoch 9/20
1800/1800 - 1s - loss: 0.0530 - accuracy: 0.9859 - 1s/epoch - 813us/step
Epoch 10/20
1800/1800 - 1s - loss: 0.0461 - accuracy: 0.9878 - 1s/epoch - 818us/step
Epoch 11/20
1800/1800 - 2s - loss: 0.0393 - accuracy: 0.9899 - 2s/epoch - 858us/step
Epoch 12/20
1800/1800 - 1s - loss: 0.0343 - accuracy: 0.9914 - 1s/epoch - 818us/step
Epoch 13/20
1800/1800 - 1s - loss: 0.0297 - accuracy: 0.9931 - 1s/epoch - 808us/step
Epoch 14/20
1800/1800 - 2s - loss: 0.0255 - accuracy: 0.9940 - 2s/epoch - 833us/step
Epoch 15/20
1800/1800 - 2s - loss: 0.0221 - accuracy: 0.9955 - 2s/epoch

Epoch 1/20
1800/1800 - 2s - loss: 0.4299 - accuracy: 0.8901 - 2s/epoch - 1ms/step
Epoch 2/20
1800/1800 - 2s - loss: 0.2093 - accuracy: 0.9399 - 2s/epoch - 951us/step
Epoch 3/20
1800/1800 - 2s - loss: 0.1577 - accuracy: 0.9545 - 2s/epoch - 925us/step
Epoch 4/20
1800/1800 - 2s - loss: 0.1249 - accuracy: 0.9646 - 2s/epoch - 940us/step
Epoch 5/20
1800/1800 - 2s - loss: 0.1022 - accuracy: 0.9714 - 2s/epoch - 954us/step
Epoch 6/20
1800/1800 - 2s - loss: 0.0852 - accuracy: 0.9760 - 2s/epoch - 906us/step
Epoch 7/20
1800/1800 - 1s - loss: 0.0719 - accuracy: 0.9797 - 1s/epoch - 831us/step
Epoch 8/20
1800/1800 - 2s - loss: 0.0610 - accuracy: 0.9827 - 2s/epoch - 882us/step
Epoch 9/20
1800/1800 - 2s - loss: 0.0524 - accuracy: 0.9858 - 2s/epoch - 1ms/step
Epoch 10/20
1800/1800 - 2s - loss: 0.0449 - accuracy: 0.9880 - 2s/epoch - 996us/step
Epoch 11/20
1800/1800 - 2s - loss: 0.0385 - accuracy: 0.9902 - 2s/epoch - 962us/step
Epoch 12/20
1800/1800 - 2s - loss: 0.0331 - accuracy: 0.9920 - 2s/epoch - 978u

Epoch 8/10
1080/1080 - 1s - loss: 0.0793 - accuracy: 0.9782 - 894ms/epoch - 828us/step
Epoch 9/10
1080/1080 - 1s - loss: 0.0690 - accuracy: 0.9815 - 876ms/epoch - 811us/step
Epoch 10/10
1080/1080 - 1s - loss: 0.0609 - accuracy: 0.9839 - 889ms/epoch - 823us/step
Epoch 1/10
1080/1080 - 1s - loss: 0.5010 - accuracy: 0.8754 - 1s/epoch - 993us/step
Epoch 2/10
1080/1080 - 1s - loss: 0.2379 - accuracy: 0.9328 - 920ms/epoch - 852us/step
Epoch 3/10
1080/1080 - 1s - loss: 0.1833 - accuracy: 0.9478 - 931ms/epoch - 862us/step
Epoch 4/10
1080/1080 - 1s - loss: 0.1491 - accuracy: 0.9572 - 958ms/epoch - 887us/step
Epoch 5/10
1080/1080 - 1s - loss: 0.1242 - accuracy: 0.9656 - 881ms/epoch - 816us/step
Epoch 6/10
1080/1080 - 1s - loss: 0.1052 - accuracy: 0.9709 - 871ms/epoch - 807us/step
Epoch 7/10
1080/1080 - 1s - loss: 0.0903 - accuracy: 0.9750 - 897ms/epoch - 830us/step
Epoch 8/10
1080/1080 - 1s - loss: 0.0784 - accuracy: 0.9780 - 888ms/epoch - 822us/step
Epoch 9/10
1080/1080 - 1s - loss: 0.0682 - ac

Epoch 5/15
1080/1080 - 1s - loss: 0.1253 - accuracy: 0.9648 - 965ms/epoch - 893us/step
Epoch 6/15
1080/1080 - 1s - loss: 0.1066 - accuracy: 0.9701 - 1s/epoch - 932us/step
Epoch 7/15
1080/1080 - 1s - loss: 0.0921 - accuracy: 0.9740 - 942ms/epoch - 872us/step
Epoch 8/15
1080/1080 - 1s - loss: 0.0802 - accuracy: 0.9780 - 960ms/epoch - 889us/step
Epoch 9/15
1080/1080 - 1s - loss: 0.0703 - accuracy: 0.9806 - 1s/epoch - 934us/step
Epoch 10/15
1080/1080 - 1s - loss: 0.0620 - accuracy: 0.9835 - 948ms/epoch - 877us/step
Epoch 11/15
1080/1080 - 1s - loss: 0.0544 - accuracy: 0.9854 - 968ms/epoch - 897us/step
Epoch 12/15
1080/1080 - 1s - loss: 0.0484 - accuracy: 0.9870 - 964ms/epoch - 892us/step
Epoch 13/15
1080/1080 - 1s - loss: 0.0431 - accuracy: 0.9890 - 1s/epoch - 928us/step
Epoch 14/15
1080/1080 - 1s - loss: 0.0379 - accuracy: 0.9907 - 954ms/epoch - 883us/step
Epoch 15/15
1080/1080 - 1s - loss: 0.0339 - accuracy: 0.9918 - 958ms/epoch - 887us/step
Epoch 1/15
1080/1080 - 1s - loss: 0.4971 - acc

Epoch 10/15
1080/1080 - 1s - loss: 0.0594 - accuracy: 0.9842 - 1s/epoch - 1ms/step
Epoch 11/15
1080/1080 - 1s - loss: 0.0521 - accuracy: 0.9865 - 1s/epoch - 984us/step
Epoch 12/15
1080/1080 - 1s - loss: 0.0461 - accuracy: 0.9881 - 1s/epoch - 962us/step
Epoch 13/15
1080/1080 - 1s - loss: 0.0408 - accuracy: 0.9892 - 1s/epoch - 962us/step
Epoch 14/15
1080/1080 - 1s - loss: 0.0361 - accuracy: 0.9910 - 1s/epoch - 977us/step
Epoch 15/15
1080/1080 - 1s - loss: 0.0315 - accuracy: 0.9928 - 1s/epoch - 954us/step
Epoch 1/15
1080/1080 - 2s - loss: 0.5142 - accuracy: 0.8723 - 2s/epoch - 2ms/step
Epoch 2/15
1080/1080 - 1s - loss: 0.2419 - accuracy: 0.9315 - 1s/epoch - 1ms/step
Epoch 3/15
1080/1080 - 1s - loss: 0.1859 - accuracy: 0.9467 - 1s/epoch - 1ms/step
Epoch 4/15
1080/1080 - 1s - loss: 0.1505 - accuracy: 0.9564 - 1s/epoch - 1ms/step
Epoch 5/15
1080/1080 - 1s - loss: 0.1256 - accuracy: 0.9640 - 1s/epoch - 1ms/step
Epoch 6/15
1080/1080 - 1s - loss: 0.1071 - accuracy: 0.9694 - 1s/epoch - 1ms/step


Epoch 18/20
1080/1080 - 1s - loss: 0.0231 - accuracy: 0.9959 - 1s/epoch - 928us/step
Epoch 19/20
1080/1080 - 1s - loss: 0.0202 - accuracy: 0.9966 - 963ms/epoch - 892us/step
Epoch 20/20
1080/1080 - 1s - loss: 0.0179 - accuracy: 0.9971 - 962ms/epoch - 890us/step
Epoch 1/20
1080/1080 - 1s - loss: 0.4928 - accuracy: 0.8784 - 1s/epoch - 1ms/step
Epoch 2/20
1080/1080 - 1s - loss: 0.2347 - accuracy: 0.9344 - 1s/epoch - 1ms/step
Epoch 3/20
1080/1080 - 1s - loss: 0.1812 - accuracy: 0.9481 - 999ms/epoch - 925us/step
Epoch 4/20
1080/1080 - 1s - loss: 0.1473 - accuracy: 0.9579 - 991ms/epoch - 918us/step
Epoch 5/20
1080/1080 - 1s - loss: 0.1228 - accuracy: 0.9651 - 993ms/epoch - 919us/step
Epoch 6/20
1080/1080 - 1s - loss: 0.1041 - accuracy: 0.9707 - 990ms/epoch - 917us/step
Epoch 7/20
1080/1080 - 1s - loss: 0.0897 - accuracy: 0.9748 - 1s/epoch - 930us/step
Epoch 8/20
1080/1080 - 1s - loss: 0.0783 - accuracy: 0.9777 - 998ms/epoch - 924us/step
Epoch 9/20
1080/1080 - 1s - loss: 0.0685 - accuracy: 0.9

Epoch 13/20
1080/1080 - 1s - loss: 0.0409 - accuracy: 0.9898 - 933ms/epoch - 864us/step
Epoch 14/20
1080/1080 - 1s - loss: 0.0364 - accuracy: 0.9912 - 975ms/epoch - 903us/step
Epoch 15/20
1080/1080 - 1s - loss: 0.0322 - accuracy: 0.9928 - 927ms/epoch - 858us/step
Epoch 16/20
1080/1080 - 1s - loss: 0.0281 - accuracy: 0.9938 - 929ms/epoch - 860us/step
Epoch 17/20
1080/1080 - 1s - loss: 0.0246 - accuracy: 0.9947 - 925ms/epoch - 856us/step
Epoch 18/20
1080/1080 - 1s - loss: 0.0219 - accuracy: 0.9956 - 985ms/epoch - 912us/step
Epoch 19/20
1080/1080 - 1s - loss: 0.0192 - accuracy: 0.9965 - 934ms/epoch - 865us/step
Epoch 20/20
1080/1080 - 1s - loss: 0.0168 - accuracy: 0.9971 - 933ms/epoch - 864us/step
Epoch 1/20
1080/1080 - 1s - loss: 0.5037 - accuracy: 0.8737 - 1s/epoch - 1ms/step
Epoch 2/20
1080/1080 - 1s - loss: 0.2434 - accuracy: 0.9308 - 1s/epoch - 939us/step
Epoch 3/20
1080/1080 - 1s - loss: 0.1878 - accuracy: 0.9463 - 920ms/epoch - 852us/step
Epoch 4/20
1080/1080 - 1s - loss: 0.1524 - 

Epoch 1/10
540/540 - 1s - loss: 0.5989 - accuracy: 0.8618 - 819ms/epoch - 2ms/step
Epoch 2/10
540/540 - 1s - loss: 0.2746 - accuracy: 0.9238 - 652ms/epoch - 1ms/step
Epoch 3/10
540/540 - 1s - loss: 0.2193 - accuracy: 0.9381 - 628ms/epoch - 1ms/step
Epoch 4/10
540/540 - 1s - loss: 0.1844 - accuracy: 0.9474 - 614ms/epoch - 1ms/step
Epoch 5/10
540/540 - 1s - loss: 0.1588 - accuracy: 0.9549 - 661ms/epoch - 1ms/step
Epoch 6/10
540/540 - 1s - loss: 0.1390 - accuracy: 0.9607 - 632ms/epoch - 1ms/step
Epoch 7/10
540/540 - 1s - loss: 0.1232 - accuracy: 0.9653 - 615ms/epoch - 1ms/step
Epoch 8/10
540/540 - 1s - loss: 0.1095 - accuracy: 0.9690 - 618ms/epoch - 1ms/step
Epoch 9/10
540/540 - 1s - loss: 0.0986 - accuracy: 0.9721 - 636ms/epoch - 1ms/step
Epoch 10/10
540/540 - 1s - loss: 0.0894 - accuracy: 0.9756 - 649ms/epoch - 1ms/step
Epoch 1/10
540/540 - 1s - loss: 0.6261 - accuracy: 0.8545 - 835ms/epoch - 2ms/step
Epoch 2/10
540/540 - 1s - loss: 0.2803 - accuracy: 0.9221 - 678ms/epoch - 1ms/step
Epo

Epoch 10/15
540/540 - 1s - loss: 0.0905 - accuracy: 0.9751 - 609ms/epoch - 1ms/step
Epoch 11/15
540/540 - 1s - loss: 0.0825 - accuracy: 0.9771 - 619ms/epoch - 1ms/step
Epoch 12/15
540/540 - 1s - loss: 0.0749 - accuracy: 0.9794 - 581ms/epoch - 1ms/step
Epoch 13/15
540/540 - 1s - loss: 0.0678 - accuracy: 0.9818 - 573ms/epoch - 1ms/step
Epoch 14/15
540/540 - 1s - loss: 0.0621 - accuracy: 0.9831 - 576ms/epoch - 1ms/step
Epoch 15/15
540/540 - 1s - loss: 0.0566 - accuracy: 0.9851 - 579ms/epoch - 1ms/step
Epoch 1/15
540/540 - 1s - loss: 0.6137 - accuracy: 0.8573 - 771ms/epoch - 1ms/step
Epoch 2/15
540/540 - 1s - loss: 0.2764 - accuracy: 0.9225 - 605ms/epoch - 1ms/step
Epoch 3/15
540/540 - 1s - loss: 0.2205 - accuracy: 0.9378 - 614ms/epoch - 1ms/step
Epoch 4/15
540/540 - 1s - loss: 0.1852 - accuracy: 0.9469 - 598ms/epoch - 1ms/step
Epoch 5/15
540/540 - 1s - loss: 0.1595 - accuracy: 0.9544 - 596ms/epoch - 1ms/step
Epoch 6/15
540/540 - 1s - loss: 0.1390 - accuracy: 0.9600 - 588ms/epoch - 1ms/ste

Epoch 19/20
540/540 - 1s - loss: 0.0384 - accuracy: 0.9908 - 628ms/epoch - 1ms/step
Epoch 20/20
540/540 - 1s - loss: 0.0351 - accuracy: 0.9919 - 694ms/epoch - 1ms/step
Epoch 1/20
540/540 - 1s - loss: 0.6279 - accuracy: 0.8536 - 863ms/epoch - 2ms/step
Epoch 2/20
540/540 - 1s - loss: 0.2813 - accuracy: 0.9213 - 695ms/epoch - 1ms/step
Epoch 3/20
540/540 - 1s - loss: 0.2225 - accuracy: 0.9378 - 685ms/epoch - 1ms/step
Epoch 4/20
540/540 - 1s - loss: 0.1870 - accuracy: 0.9473 - 649ms/epoch - 1ms/step
Epoch 5/20
540/540 - 1s - loss: 0.1613 - accuracy: 0.9540 - 647ms/epoch - 1ms/step
Epoch 6/20
540/540 - 1s - loss: 0.1413 - accuracy: 0.9602 - 645ms/epoch - 1ms/step
Epoch 7/20
540/540 - 1s - loss: 0.1248 - accuracy: 0.9648 - 624ms/epoch - 1ms/step
Epoch 8/20
540/540 - 1s - loss: 0.1114 - accuracy: 0.9695 - 627ms/epoch - 1ms/step
Epoch 9/20
540/540 - 1s - loss: 0.0997 - accuracy: 0.9724 - 631ms/epoch - 1ms/step
Epoch 10/20
540/540 - 1s - loss: 0.0896 - accuracy: 0.9751 - 631ms/epoch - 1ms/step
E

540/540 - 1s - loss: 0.0441 - accuracy: 0.9885 - 591ms/epoch - 1ms/step
Epoch 18/20
540/540 - 1s - loss: 0.0402 - accuracy: 0.9900 - 594ms/epoch - 1ms/step
Epoch 19/20
540/540 - 1s - loss: 0.0369 - accuracy: 0.9912 - 591ms/epoch - 1ms/step
Epoch 20/20
540/540 - 1s - loss: 0.0337 - accuracy: 0.9919 - 598ms/epoch - 1ms/step
Epoch 1/20
540/540 - 1s - loss: 0.6028 - accuracy: 0.8586 - 776ms/epoch - 1ms/step
Epoch 2/20
540/540 - 1s - loss: 0.2755 - accuracy: 0.9237 - 604ms/epoch - 1ms/step
Epoch 3/20
540/540 - 1s - loss: 0.2180 - accuracy: 0.9389 - 635ms/epoch - 1ms/step
Epoch 4/20
540/540 - 1s - loss: 0.1828 - accuracy: 0.9477 - 618ms/epoch - 1ms/step
Epoch 5/20
540/540 - 1s - loss: 0.1567 - accuracy: 0.9548 - 600ms/epoch - 1ms/step
Epoch 6/20
540/540 - 1s - loss: 0.1369 - accuracy: 0.9613 - 589ms/epoch - 1ms/step
Epoch 7/20
540/540 - 1s - loss: 0.1212 - accuracy: 0.9655 - 588ms/epoch - 1ms/step
Epoch 8/20
540/540 - 1s - loss: 0.1082 - accuracy: 0.9694 - 591ms/epoch - 1ms/step
Epoch 9/20
5

Epoch 15/20
1200/1200 - 1s - loss: 0.0306 - accuracy: 0.9929 - 997ms/epoch - 831us/step
Epoch 16/20
1200/1200 - 1s - loss: 0.0267 - accuracy: 0.9943 - 995ms/epoch - 829us/step
Epoch 17/20
1200/1200 - 1s - loss: 0.0240 - accuracy: 0.9953 - 999ms/epoch - 832us/step
Epoch 18/20
1200/1200 - 1s - loss: 0.0210 - accuracy: 0.9960 - 998ms/epoch - 832us/step
Epoch 19/20
1200/1200 - 1s - loss: 0.0185 - accuracy: 0.9968 - 995ms/epoch - 829us/step
Epoch 20/20
1200/1200 - 1s - loss: 0.0161 - accuracy: 0.9974 - 1s/epoch - 852us/step


GridSearchCV(cv=10,
             estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x000001339DB86670>,
             param_grid={'batch_size': [30, 50, 100], 'epochs': [10, 15, 20]},
             scoring='neg_log_loss')

In [165]:
#8- Based on your results, what is the best batch_size and epochs?   
#Now, test your model with the best batch_size and epochs on the testing set.   grid.best_estimator_.model  gives you the best model found and trained in the grid-search. 
#What is the prediction accuracy on the testing set?

gridTest = GridSearchCV(model, param_grid, cv = 10, scoring = 'neg_log_loss')
gridTest.fit(X_test, y_test)



Epoch 1/10
300/300 - 0s - loss: 0.8919 - accuracy: 0.8071 - 477ms/epoch - 2ms/step
Epoch 2/10
300/300 - 0s - loss: 0.3957 - accuracy: 0.8994 - 292ms/epoch - 974us/step
Epoch 3/10
300/300 - 0s - loss: 0.3029 - accuracy: 0.9209 - 275ms/epoch - 917us/step
Epoch 4/10
300/300 - 0s - loss: 0.2545 - accuracy: 0.9312 - 272ms/epoch - 907us/step
Epoch 5/10
300/300 - 0s - loss: 0.2213 - accuracy: 0.9390 - 270ms/epoch - 901us/step
Epoch 6/10
300/300 - 0s - loss: 0.1964 - accuracy: 0.9456 - 269ms/epoch - 897us/step
Epoch 7/10
300/300 - 0s - loss: 0.1743 - accuracy: 0.9526 - 268ms/epoch - 894us/step
Epoch 8/10
300/300 - 0s - loss: 0.1581 - accuracy: 0.9569 - 269ms/epoch - 897us/step
Epoch 9/10
300/300 - 0s - loss: 0.1404 - accuracy: 0.9619 - 281ms/epoch - 938us/step
Epoch 10/10
300/300 - 0s - loss: 0.1263 - accuracy: 0.9663 - 279ms/epoch - 931us/step
Epoch 1/10
300/300 - 0s - loss: 0.9069 - accuracy: 0.8110 - 450ms/epoch - 2ms/step
Epoch 2/10
300/300 - 0s - loss: 0.3919 - accuracy: 0.9041 - 271ms/ep

Epoch 8/10
300/300 - 0s - loss: 0.1540 - accuracy: 0.9588 - 285ms/epoch - 951us/step
Epoch 9/10
300/300 - 0s - loss: 0.1381 - accuracy: 0.9629 - 287ms/epoch - 958us/step
Epoch 10/10
300/300 - 0s - loss: 0.1228 - accuracy: 0.9686 - 286ms/epoch - 954us/step
Epoch 1/15
300/300 - 0s - loss: 0.9078 - accuracy: 0.8069 - 459ms/epoch - 2ms/step
Epoch 2/15
300/300 - 0s - loss: 0.3942 - accuracy: 0.9029 - 273ms/epoch - 911us/step
Epoch 3/15
300/300 - 0s - loss: 0.3036 - accuracy: 0.9218 - 276ms/epoch - 921us/step
Epoch 4/15
300/300 - 0s - loss: 0.2569 - accuracy: 0.9316 - 281ms/epoch - 938us/step
Epoch 5/15
300/300 - 0s - loss: 0.2249 - accuracy: 0.9373 - 285ms/epoch - 951us/step
Epoch 6/15
300/300 - 0s - loss: 0.1986 - accuracy: 0.9449 - 287ms/epoch - 958us/step
Epoch 7/15
300/300 - 0s - loss: 0.1779 - accuracy: 0.9521 - 286ms/epoch - 954us/step
Epoch 8/15
300/300 - 0s - loss: 0.1594 - accuracy: 0.9577 - 286ms/epoch - 954us/step
Epoch 9/15
300/300 - 0s - loss: 0.1422 - accuracy: 0.9630 - 283ms/

300/300 - 0s - loss: 0.2620 - accuracy: 0.9282 - 278ms/epoch - 928us/step
Epoch 5/15
300/300 - 0s - loss: 0.2287 - accuracy: 0.9362 - 279ms/epoch - 931us/step
Epoch 6/15
300/300 - 0s - loss: 0.2012 - accuracy: 0.9448 - 277ms/epoch - 924us/step
Epoch 7/15
300/300 - 0s - loss: 0.1792 - accuracy: 0.9501 - 276ms/epoch - 921us/step
Epoch 8/15
300/300 - 0s - loss: 0.1590 - accuracy: 0.9566 - 278ms/epoch - 928us/step
Epoch 9/15
300/300 - 0s - loss: 0.1424 - accuracy: 0.9619 - 280ms/epoch - 934us/step
Epoch 10/15
300/300 - 0s - loss: 0.1277 - accuracy: 0.9639 - 279ms/epoch - 931us/step
Epoch 11/15
300/300 - 0s - loss: 0.1141 - accuracy: 0.9706 - 284ms/epoch - 948us/step
Epoch 12/15
300/300 - 0s - loss: 0.1024 - accuracy: 0.9736 - 281ms/epoch - 938us/step
Epoch 13/15
300/300 - 0s - loss: 0.0920 - accuracy: 0.9768 - 266ms/epoch - 887us/step
Epoch 14/15
300/300 - 0s - loss: 0.0820 - accuracy: 0.9797 - 264ms/epoch - 881us/step
Epoch 15/15
300/300 - 0s - loss: 0.0738 - accuracy: 0.9827 - 263ms/epoc

300/300 - 0s - loss: 0.0369 - accuracy: 0.9947 - 263ms/epoch - 877us/step
Epoch 1/20
300/300 - 0s - loss: 0.9406 - accuracy: 0.7944 - 446ms/epoch - 1ms/step
Epoch 2/20
300/300 - 0s - loss: 0.3975 - accuracy: 0.9012 - 265ms/epoch - 884us/step
Epoch 3/20
300/300 - 0s - loss: 0.2976 - accuracy: 0.9214 - 264ms/epoch - 881us/step
Epoch 4/20
300/300 - 0s - loss: 0.2487 - accuracy: 0.9328 - 275ms/epoch - 918us/step
Epoch 5/20
300/300 - 0s - loss: 0.2162 - accuracy: 0.9407 - 278ms/epoch - 928us/step
Epoch 6/20
300/300 - 0s - loss: 0.1918 - accuracy: 0.9461 - 277ms/epoch - 924us/step
Epoch 7/20
300/300 - 0s - loss: 0.1706 - accuracy: 0.9520 - 276ms/epoch - 921us/step
Epoch 8/20
300/300 - 0s - loss: 0.1523 - accuracy: 0.9579 - 277ms/epoch - 924us/step
Epoch 9/20
300/300 - 0s - loss: 0.1367 - accuracy: 0.9636 - 276ms/epoch - 921us/step
Epoch 10/20
300/300 - 0s - loss: 0.1232 - accuracy: 0.9662 - 276ms/epoch - 921us/step
Epoch 11/20
300/300 - 0s - loss: 0.1103 - accuracy: 0.9716 - 270ms/epoch - 90

300/300 - 0s - loss: 0.0670 - accuracy: 0.9852 - 263ms/epoch - 877us/step
Epoch 17/20
300/300 - 0s - loss: 0.0609 - accuracy: 0.9868 - 264ms/epoch - 881us/step
Epoch 18/20
300/300 - 0s - loss: 0.0540 - accuracy: 0.9893 - 262ms/epoch - 874us/step
Epoch 19/20
300/300 - 0s - loss: 0.0474 - accuracy: 0.9918 - 265ms/epoch - 884us/step
Epoch 20/20
300/300 - 0s - loss: 0.0427 - accuracy: 0.9926 - 263ms/epoch - 877us/step
Epoch 1/20
300/300 - 0s - loss: 0.9470 - accuracy: 0.7819 - 441ms/epoch - 1ms/step
Epoch 2/20
300/300 - 0s - loss: 0.4174 - accuracy: 0.8944 - 253ms/epoch - 844us/step
Epoch 3/20
300/300 - 0s - loss: 0.3175 - accuracy: 0.9139 - 255ms/epoch - 851us/step
Epoch 4/20
300/300 - 0s - loss: 0.2679 - accuracy: 0.9258 - 252ms/epoch - 841us/step
Epoch 5/20
300/300 - 0s - loss: 0.2354 - accuracy: 0.9341 - 262ms/epoch - 874us/step
Epoch 6/20
300/300 - 0s - loss: 0.2063 - accuracy: 0.9412 - 265ms/epoch - 884us/step
Epoch 7/20
300/300 - 0s - loss: 0.1847 - accuracy: 0.9487 - 268ms/epoch - 

Epoch 3/10
180/180 - 0s - loss: 0.3527 - accuracy: 0.9120 - 178ms/epoch - 990us/step
Epoch 4/10
180/180 - 0s - loss: 0.2934 - accuracy: 0.9216 - 179ms/epoch - 995us/step
Epoch 5/10
180/180 - 0s - loss: 0.2549 - accuracy: 0.9310 - 178ms/epoch - 990us/step
Epoch 6/10
180/180 - 0s - loss: 0.2283 - accuracy: 0.9393 - 178ms/epoch - 990us/step
Epoch 7/10
180/180 - 0s - loss: 0.2064 - accuracy: 0.9421 - 185ms/epoch - 1ms/step
Epoch 8/10
180/180 - 0s - loss: 0.1870 - accuracy: 0.9479 - 184ms/epoch - 1ms/step
Epoch 9/10
180/180 - 0s - loss: 0.1706 - accuracy: 0.9543 - 183ms/epoch - 1ms/step
Epoch 10/10
180/180 - 0s - loss: 0.1568 - accuracy: 0.9582 - 182ms/epoch - 1ms/step
Epoch 1/10
180/180 - 0s - loss: 1.0444 - accuracy: 0.7781 - 357ms/epoch - 2ms/step
Epoch 2/10
180/180 - 0s - loss: 0.4650 - accuracy: 0.8920 - 175ms/epoch - 973us/step
Epoch 3/10
180/180 - 0s - loss: 0.3430 - accuracy: 0.9131 - 176ms/epoch - 979us/step
Epoch 4/10
180/180 - 0s - loss: 0.2851 - accuracy: 0.9233 - 175ms/epoch - 

180/180 - 0s - loss: 0.1037 - accuracy: 0.9744 - 166ms/epoch - 923us/step
Epoch 1/15
180/180 - 0s - loss: 1.0908 - accuracy: 0.7712 - 341ms/epoch - 2ms/step
Epoch 2/15
180/180 - 0s - loss: 0.4756 - accuracy: 0.8912 - 156ms/epoch - 867us/step
Epoch 3/15
180/180 - 0s - loss: 0.3509 - accuracy: 0.9118 - 156ms/epoch - 867us/step
Epoch 4/15
180/180 - 0s - loss: 0.2916 - accuracy: 0.9224 - 157ms/epoch - 873us/step
Epoch 5/15
180/180 - 0s - loss: 0.2551 - accuracy: 0.9311 - 156ms/epoch - 867us/step
Epoch 6/15
180/180 - 0s - loss: 0.2276 - accuracy: 0.9389 - 157ms/epoch - 873us/step
Epoch 7/15
180/180 - 0s - loss: 0.2059 - accuracy: 0.9437 - 157ms/epoch - 873us/step
Epoch 8/15
180/180 - 0s - loss: 0.1866 - accuracy: 0.9501 - 158ms/epoch - 879us/step
Epoch 9/15
180/180 - 0s - loss: 0.1707 - accuracy: 0.9532 - 176ms/epoch - 979us/step
Epoch 10/15
180/180 - 0s - loss: 0.1560 - accuracy: 0.9586 - 196ms/epoch - 1ms/step
Epoch 11/15
180/180 - 0s - loss: 0.1429 - accuracy: 0.9633 - 235ms/epoch - 1ms/

Epoch 8/15
180/180 - 0s - loss: 0.2064 - accuracy: 0.9430 - 187ms/epoch - 1ms/step
Epoch 9/15
180/180 - 0s - loss: 0.1892 - accuracy: 0.9492 - 183ms/epoch - 1ms/step
Epoch 10/15
180/180 - 0s - loss: 0.1742 - accuracy: 0.9519 - 197ms/epoch - 1ms/step
Epoch 11/15
180/180 - 0s - loss: 0.1604 - accuracy: 0.9573 - 187ms/epoch - 1ms/step
Epoch 12/15
180/180 - 0s - loss: 0.1475 - accuracy: 0.9610 - 184ms/epoch - 1ms/step
Epoch 13/15
180/180 - 0s - loss: 0.1348 - accuracy: 0.9656 - 177ms/epoch - 984us/step
Epoch 14/15
180/180 - 0s - loss: 0.1251 - accuracy: 0.9684 - 178ms/epoch - 990us/step
Epoch 15/15
180/180 - 0s - loss: 0.1157 - accuracy: 0.9708 - 173ms/epoch - 962us/step
Epoch 1/15
180/180 - 0s - loss: 1.1277 - accuracy: 0.7476 - 365ms/epoch - 2ms/step
Epoch 2/15
180/180 - 0s - loss: 0.4925 - accuracy: 0.8872 - 180ms/epoch - 1ms/step
Epoch 3/15
180/180 - 0s - loss: 0.3631 - accuracy: 0.9070 - 184ms/epoch - 1ms/step
Epoch 4/15
180/180 - 0s - loss: 0.3013 - accuracy: 0.9207 - 182ms/epoch - 1

180/180 - 0s - loss: 0.0979 - accuracy: 0.9757 - 170ms/epoch - 945us/step
Epoch 16/20
180/180 - 0s - loss: 0.0904 - accuracy: 0.9770 - 171ms/epoch - 951us/step
Epoch 17/20
180/180 - 0s - loss: 0.0821 - accuracy: 0.9822 - 172ms/epoch - 956us/step
Epoch 18/20
180/180 - 0s - loss: 0.0757 - accuracy: 0.9830 - 171ms/epoch - 951us/step
Epoch 19/20
180/180 - 0s - loss: 0.0690 - accuracy: 0.9836 - 169ms/epoch - 940us/step
Epoch 20/20
180/180 - 0s - loss: 0.0636 - accuracy: 0.9864 - 169ms/epoch - 940us/step
Epoch 1/20
180/180 - 0s - loss: 1.1322 - accuracy: 0.7600 - 352ms/epoch - 2ms/step
Epoch 2/20
180/180 - 0s - loss: 0.4851 - accuracy: 0.8910 - 171ms/epoch - 951us/step
Epoch 3/20
180/180 - 0s - loss: 0.3526 - accuracy: 0.9121 - 171ms/epoch - 951us/step
Epoch 4/20
180/180 - 0s - loss: 0.2922 - accuracy: 0.9231 - 169ms/epoch - 940us/step
Epoch 5/20
180/180 - 0s - loss: 0.2546 - accuracy: 0.9320 - 170ms/epoch - 945us/step
Epoch 6/20
180/180 - 0s - loss: 0.2274 - accuracy: 0.9389 - 170ms/epoch -

Epoch 12/20
180/180 - 0s - loss: 0.1443 - accuracy: 0.9630 - 163ms/epoch - 906us/step
Epoch 13/20
180/180 - 0s - loss: 0.1331 - accuracy: 0.9646 - 162ms/epoch - 901us/step
Epoch 14/20
180/180 - 0s - loss: 0.1223 - accuracy: 0.9694 - 162ms/epoch - 901us/step
Epoch 15/20
180/180 - 0s - loss: 0.1127 - accuracy: 0.9713 - 164ms/epoch - 912us/step
Epoch 16/20
180/180 - 0s - loss: 0.1040 - accuracy: 0.9754 - 163ms/epoch - 906us/step
Epoch 17/20
180/180 - 0s - loss: 0.0960 - accuracy: 0.9777 - 160ms/epoch - 890us/step
Epoch 18/20
180/180 - 0s - loss: 0.0874 - accuracy: 0.9801 - 162ms/epoch - 901us/step
Epoch 19/20
180/180 - 0s - loss: 0.0810 - accuracy: 0.9818 - 165ms/epoch - 917us/step
Epoch 20/20
180/180 - 0s - loss: 0.0741 - accuracy: 0.9837 - 162ms/epoch - 901us/step
Epoch 1/20
180/180 - 0s - loss: 1.0773 - accuracy: 0.7800 - 338ms/epoch - 2ms/step
Epoch 2/20
180/180 - 0s - loss: 0.4806 - accuracy: 0.8906 - 153ms/epoch - 851us/step
Epoch 3/20
180/180 - 0s - loss: 0.3580 - accuracy: 0.9094 

Epoch 2/10
90/90 - 0s - loss: 0.6464 - accuracy: 0.8662 - 107ms/epoch - 1ms/step
Epoch 3/10
90/90 - 0s - loss: 0.4661 - accuracy: 0.8904 - 106ms/epoch - 1ms/step
Epoch 4/10
90/90 - 0s - loss: 0.3825 - accuracy: 0.9044 - 108ms/epoch - 1ms/step
Epoch 5/10
90/90 - 0s - loss: 0.3328 - accuracy: 0.9121 - 107ms/epoch - 1ms/step
Epoch 6/10
90/90 - 0s - loss: 0.2979 - accuracy: 0.9190 - 107ms/epoch - 1ms/step
Epoch 7/10
90/90 - 0s - loss: 0.2714 - accuracy: 0.9266 - 106ms/epoch - 1ms/step
Epoch 8/10
90/90 - 0s - loss: 0.2521 - accuracy: 0.9322 - 107ms/epoch - 1ms/step
Epoch 9/10
90/90 - 0s - loss: 0.2339 - accuracy: 0.9376 - 108ms/epoch - 1ms/step
Epoch 10/10
90/90 - 0s - loss: 0.2185 - accuracy: 0.9421 - 105ms/epoch - 1ms/step
Epoch 1/10
90/90 - 0s - loss: 1.3507 - accuracy: 0.7153 - 289ms/epoch - 3ms/step
Epoch 2/10
90/90 - 0s - loss: 0.6575 - accuracy: 0.8654 - 107ms/epoch - 1ms/step
Epoch 3/10
90/90 - 0s - loss: 0.4770 - accuracy: 0.8901 - 108ms/epoch - 1ms/step
Epoch 4/10
90/90 - 0s - los

Epoch 13/15
90/90 - 0s - loss: 0.1708 - accuracy: 0.9552 - 107ms/epoch - 1ms/step
Epoch 14/15
90/90 - 0s - loss: 0.1609 - accuracy: 0.9574 - 106ms/epoch - 1ms/step
Epoch 15/15
90/90 - 0s - loss: 0.1504 - accuracy: 0.9612 - 107ms/epoch - 1ms/step
Epoch 1/15
90/90 - 0s - loss: 1.3451 - accuracy: 0.7213 - 287ms/epoch - 3ms/step
Epoch 2/15
90/90 - 0s - loss: 0.6497 - accuracy: 0.8631 - 110ms/epoch - 1ms/step
Epoch 3/15
90/90 - 0s - loss: 0.4668 - accuracy: 0.8904 - 110ms/epoch - 1ms/step
Epoch 4/15
90/90 - 0s - loss: 0.3841 - accuracy: 0.9042 - 110ms/epoch - 1ms/step
Epoch 5/15
90/90 - 0s - loss: 0.3336 - accuracy: 0.9118 - 108ms/epoch - 1ms/step
Epoch 6/15
90/90 - 0s - loss: 0.2995 - accuracy: 0.9186 - 111ms/epoch - 1ms/step
Epoch 7/15
90/90 - 0s - loss: 0.2737 - accuracy: 0.9256 - 111ms/epoch - 1ms/step
Epoch 8/15
90/90 - 0s - loss: 0.2513 - accuracy: 0.9293 - 109ms/epoch - 1ms/step
Epoch 9/15
90/90 - 0s - loss: 0.2344 - accuracy: 0.9344 - 110ms/epoch - 1ms/step
Epoch 10/15
90/90 - 0s - 

Epoch 4/20
90/90 - 0s - loss: 0.3707 - accuracy: 0.9099 - 111ms/epoch - 1ms/step
Epoch 5/20
90/90 - 0s - loss: 0.3208 - accuracy: 0.9173 - 110ms/epoch - 1ms/step
Epoch 6/20
90/90 - 0s - loss: 0.2856 - accuracy: 0.9236 - 110ms/epoch - 1ms/step
Epoch 7/20
90/90 - 0s - loss: 0.2599 - accuracy: 0.9311 - 109ms/epoch - 1ms/step
Epoch 8/20
90/90 - 0s - loss: 0.2391 - accuracy: 0.9348 - 110ms/epoch - 1ms/step
Epoch 9/20
90/90 - 0s - loss: 0.2230 - accuracy: 0.9401 - 113ms/epoch - 1ms/step
Epoch 10/20
90/90 - 0s - loss: 0.2073 - accuracy: 0.9436 - 115ms/epoch - 1ms/step
Epoch 11/20
90/90 - 0s - loss: 0.1945 - accuracy: 0.9473 - 116ms/epoch - 1ms/step
Epoch 12/20
90/90 - 0s - loss: 0.1821 - accuracy: 0.9510 - 125ms/epoch - 1ms/step
Epoch 13/20
90/90 - 0s - loss: 0.1716 - accuracy: 0.9539 - 116ms/epoch - 1ms/step
Epoch 14/20
90/90 - 0s - loss: 0.1612 - accuracy: 0.9572 - 117ms/epoch - 1ms/step
Epoch 15/20
90/90 - 0s - loss: 0.1522 - accuracy: 0.9607 - 117ms/epoch - 1ms/step
Epoch 16/20
90/90 - 0s

Epoch 5/20
90/90 - 0s - loss: 0.3376 - accuracy: 0.9114 - 114ms/epoch - 1ms/step
Epoch 6/20
90/90 - 0s - loss: 0.3017 - accuracy: 0.9199 - 113ms/epoch - 1ms/step
Epoch 7/20
90/90 - 0s - loss: 0.2758 - accuracy: 0.9278 - 112ms/epoch - 1ms/step
Epoch 8/20
90/90 - 0s - loss: 0.2546 - accuracy: 0.9322 - 113ms/epoch - 1ms/step
Epoch 9/20
90/90 - 0s - loss: 0.2371 - accuracy: 0.9363 - 118ms/epoch - 1ms/step
Epoch 10/20
90/90 - 0s - loss: 0.2218 - accuracy: 0.9403 - 113ms/epoch - 1ms/step
Epoch 11/20
90/90 - 0s - loss: 0.2078 - accuracy: 0.9438 - 118ms/epoch - 1ms/step
Epoch 12/20
90/90 - 0s - loss: 0.1959 - accuracy: 0.9468 - 118ms/epoch - 1ms/step
Epoch 13/20
90/90 - 0s - loss: 0.1843 - accuracy: 0.9484 - 118ms/epoch - 1ms/step
Epoch 14/20
90/90 - 0s - loss: 0.1752 - accuracy: 0.9517 - 119ms/epoch - 1ms/step
Epoch 15/20
90/90 - 0s - loss: 0.1645 - accuracy: 0.9540 - 119ms/epoch - 1ms/step
Epoch 16/20
90/90 - 0s - loss: 0.1559 - accuracy: 0.9568 - 117ms/epoch - 1ms/step
Epoch 17/20
90/90 - 0

GridSearchCV(cv=10,
             estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x000001339DB86670>,
             param_grid={'batch_size': [30, 50, 100], 'epochs': [10, 15, 20]},
             scoring='neg_log_loss')

In [166]:
print("The best batch size and epoch for training set is: ", gridTrain.best_params_)
print("The best batch size and epoch for testing set is: ", gridTest.best_params_)

print("The best model from training set: ", gridTrain.best_estimator_.model)
print("the best score from training set: ", gridTrain.best_score_)

print("The best model from testing set: ", gridTest.best_estimator_.model)
print("the best score from testing set: ", gridTest.best_score_)

# Prediction:
y_predict = gridTest.predict(X_test)


#our neural network will have 10 output
y_predict = np_utils.to_categorical(y_predict, 10)

#printing out some of the prediction results and test results
#print('y_predict', y_predict[:10])
#print('y_test', y_test[:10])

#importing to get accuracy score
from sklearn.metrics import accuracy_score

# Evaluation:
score = accuracy_score(y_test, y_predict)

print('The prediction accuracy on the testing set is: ', score)



The best batch size and epoch for training set is:  {'batch_size': 50, 'epochs': 20}
The best batch size and epoch for testing set is:  {'batch_size': 30, 'epochs': 20}
The best model from training set:  <keras.engine.sequential.Sequential object at 0x000001338A9BBB80>
the best score from training set:  -0.08895485265775402
The best model from testing set:  <keras.engine.sequential.Sequential object at 0x000001338D0D0B20>
the best score from testing set:  -0.19127188453142588
The prediction accuracy on the testing set is:  0.9972
